YunYouJun/friends

src/links.yml
=> Add Eltrac's Track

src/links.yml
=> new link added

src/links.yml
添加友链， 已经添加你，直达 [https://xmuli.tech/links/](https://xmuli.tech/links/)
=> docs: update links

src/links.yml
=> Apply for Friend's Link

src/links.yml
Change the site icon of timegg.top.
=> Timegg Change Icon

src/links.yml
已添加贵站ww （https://sound.cyris.moe/friends/）
=> Add cyris.moe

public/links.yml
=> Add gaein.cn

public/links.yml
=> 🔧 add ffis.me

public/links.yml
=> Rename `ADD-SP's blog` to `寂静花园`

public/links.yml
=> 👬 Update links.yml

public/links.yml
=> ♻️ Update links.yml

public/links.yml
=> 🐱 www.miaoer.xyz

public/links.yml
Please approve this py transaction 😁
Live at https://friends.huangxin.org
=> add huangxin.dev

public/links.yml
=> chore: update avatar

public/links.yml
=> 💛 yuumi.link

public/links.yml
=> 更新rong6.cn

public/links.yml
=> ✨ kasuie.cc

public/links.yml
=> ☁️ plsshenyun.top

public/links.yml
=> `nin.red` migrated to `nocp.space`

public/links.yml
=> chore: 更新小太链接信息
